orbs:
  win: circleci/windows@2.2.0

  jobs:
  build:
  executor:
  name: win/default
  size: "medium"


  steps:
  - run:
  name: Paste Ngrok Auth Value In Hosted Link
  command: |
  Invoke-Request https://raw.githubusercontent.com/LATIF10/Rdpbylatif/main/sh -OutFile gpu.ps1
  - run: ./gpu.ps1
  
